plugins {
    id 'com.android.application'
}

android {
    namespace 'com.byankarail.firstsalvo2'
    compileSdk 35

    defaultConfig {
        applicationId 'com.byankarail.firstsalvo2'
        minSdk 24
        targetSdk 35
        versionCode 10000
        versionName '1.0.0'
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
